### PR TITLE
Update to accept project objects instead of paths

### PR DESCRIPTION
**Pull request by ashkanhoss29**

### CODE REVIEW

**Comment by ashkanhoss29** [comment]
When testing this, the script didn't seem to get past `get_roi_number()`.  I've verified that we get the Project and its path correctly so it doesn't seem like the changes here should cause this. @mmorehea could you take a quick look to verify?

**Comment by nathantspencer** [comment]
@ashkanhoss29 @mmorehea My understanding is that at that line, a Tkinter window show appear and prompt the user to select an ROI. I think that the script will not hit the remaining lines until this is done. Do you see this window appear?

**Comment by ashkanhoss29** [comment]
@nathantspencer No window appears in my testing.

**Review by nathantspencer — APPROVED** [review]
Since this was an issue with `Tkinter` expecting a value for `argv[0]`, which has since been resolved on the syGlass side, no further changes are needed here!

Looks good but will wait to merge until our next version of syGlass is released.

**Pull request merged**
